import React from "react";
import "./AIInsight.css";

const defaultInsight = {
  title: "AI Insight",
  note: "Insight is generated by AI and based solely on historical data. It does not predict future performance.",
};

function SparkleIcon() {
  return (
    <svg
      className="ai-insight__sparkle"
      viewBox="0 0 20 20"
      aria-hidden="true"
    >
      <path d="M10 2.5c.55 3.95 2.05 5.45 6 6-3.95.55-5.45 2.05-6 6-.55-3.95-2.05-5.45-6-6 3.95-.55 5.45-2.05 6-6Z" />
      <path d="M16 2.5c.2 1.35.65 1.8 2 2-.95.2-1.45.65-2 2-.2-1.35-.65-1.8-2-2 .95-.2 1.45-.65 2-2Z" />
    </svg>
  );
}

function InfoIcon() {
  return (
    <svg
      className="ai-insight__info-icon"
      viewBox="0 0 16 16"
      aria-hidden="true"
    >
      <circle cx="8" cy="8" r="5.5" />
      <path d="M8 7v3" />
      <circle cx="8" cy="4.9" r=".55" fill="currentColor" stroke="none" />
    </svg>
  );
}

export default function AIInsight({
  title = defaultInsight.title,
  body = <p>No analysis available yet.</p>,
  note = defaultInsight.note,
}) {
  return (
    <article className="ai-insight">
      <div className="ai-insight__content">
        <header className="ai-insight__header">
          <SparkleIcon />

          <h2 className="ai-insight__title">{title}</h2>
        </header>

        <div className="ai-insight__body">{body}</div>
      </div>

      <footer className="ai-insight__footer">
        <InfoIcon />

        <p className="ai-insight__note">{note}</p>
      </footer>
    </article>
  );
}